server:
  max-http-request-header-size: 64KB
spring:
  ai:
    mcp:
      server:
        enabled: true
  main:
    banner-mode: off
hapi:
  fhir:
    fhir_version: R4
    server_address: https://hapi-fhir.au.localhost/fhir
    # Enable custom search parameters
    allow_external_references: true
    allow_multiple_delete: true
    reuse_cached_search_results_millis: 60000
    tester:
      home:
        name: Local Tester
        server_address: 'http://localhost:8080/fhir'
        refuse_to_fetch_third_party_urls: false
        fhir_version: R4
