hapi:
  fhir:
    # server_address: http://localhost:8080/fhir
    server_address: http://hapi-fhir.au.localhost/fhir
    default_encoding: json
    # dao_config.server_id_mode: UUID
    implementationguides:
      au_core:
        name: hl7.fhir.au.core
        version: 1.0.0-preview
        reloadExisting: false
        installMode: STORE_AND_INSTALL
        packageUrl: https://hl7.org.au/fhir/core/1.0.0-preview/package.tgz
        fetchDependencies: true
    logical_urls:
      - http://hl7.org.au/*
      - https://hl7.org.au/*
